### ISSUE TITLE
Define requirements for the application implementation

### ISSUE THREAD

**Issue by Dayrren** [infinitymalle/Project-D0020E#11]

**Comment by LeffeSTFU** [comment]
Priority: High

Description:
Define most fo the reuirements for the implementation. This should be done as a group and has to be discussed closley.

Estimated time:
6h

**Comment by LeffeSTFU** [comment]
Malkolm and I started thinking of what should be included in the application from a communication perspective building upon our basic former communications principle.

Some application functionallity should include:

User:
Set values of PoA (Transferable, public key, time, etc)
Send to recipient
Request NEW expiration date for PoA
Send NEW PoA with requested time from agent
Pass on to next agent (if trasferable)

---------Based on old communications--------

Principal (server):
Set values of PoA (Transferable, public key, time, etc)
Send to recipient agent (client)
Send NEW PoA with requested time from agent

Agent (client):
Validate PoA
Request NEW expiration date for PoA
Pass on to next agent 

Agent 2 (client 2?):
Validate PoA
Request NEW expiration date for PoA
Pass on to next agent
